config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :profiles
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :post, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "Icon.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    authorize current_user
  end


  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new

  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :description, :user_id, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%
  @profile.user_id = current_user.id
  %>

  <div class="field">
    <%= form.label :avatar  %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field"  style="display: none;">
    <% form.label :user_id %>
    <%= form.text_area :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="barra">
  <h3 style="color:white" align="right">
  <%aux = " "%>
  <% current_user.profile.each do |item|%>
    <% aux = "/profiles/"+ item.id.to_s %>
      <% break %>
  <%end%>
  <%if user_signed_in? %>
    <%= current_user.email %> <%=link_to "Meu perfil", aux %> <%=link_to "Sair", destroy_user_session_path, method: :delete%>
  <%else%>
      <%=link_to "Entrar", new_user_session_path%>
      <%=link_to "Inscrever-se", new_user_registration_path%>

  <%end%>
  <%=link_to "Posts", posts_path%>
  </h3>
</div>
</br>
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.description %></td>
        <td><%= profile.user_id %></td>
        <td><%= profile.user.email %></td>
        <td><%= profile.user.role %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<center>
<h1>Crie seu perfil para participar</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="barra">
  <%aux = " "%>
  <h3 style="color:white" align="right">
  <%if user_signed_in? %>
    <% current_user.profile.each do |item|%>
      <% aux = "/profiles/"+ item.id.to_s %>
        <% break %>
    <%end%>
    <%= current_user.email %> <%= link_to "Meu perfil", aux %> <%=link_to "Sair", destroy_user_session_path, method: :delete%>
  <%else%>
      <%=link_to "Entrar", new_user_session_path%>
      <%=link_to "Inscrever-se", new_user_registration_path%>

  <%end%>
  <%=link_to "Posts", posts_path%>
  </h3>
</div>
</br>
<center>
<table >
  <tbody>
    <tr>
      <td width=50 rowspan="4"><%= image_tag(@profile.avatar.url(:medium))%> </td>
      <td colspan="2" height=10 style="vertical-align:bottom"><h1 style="color:black "> <%= @profile.name%> </h1></td>
    </tr>
    <tr><td colspan="2" style="vertical-align:top">
        <%=@profile.user.email%>
    </td></tr>
    <tr><td colspan="2" style="vertical-align:top">
        <%=@profile.description%>
    </td></tr>
    <tr><td colspan="2" style="vertical-align:top">
        <h2><%=link_to "Editar Perfil", edit_profile_path%><h2>
    </td></tr>
    <tr ><td colspan="2" align="center"><h1><%= link_to 'Postar', new_post_path %></h1></td></tr>
    <% @profile.post.reverse.each do |post| %>
      <tr><td colspan="3"><h2><%= post.title %></h2></td></tr>
      <tr><td colspan="3"><%= post.description %></td></tr>
      <tr><td colspan="3"><%=image_tag(post.image.url(:normal)) %></td></tr>
      <%if user_signed_in?%>
        <% current_user.profile.each do |item|%>
          <%if item.id == post.profile.id or current_user.admin?%>
            <td colspan="3">
              <%= link_to 'Mostrar', post %>
              <%= link_to 'Editar', edit_post_path(post) %>
              <%= link_to 'Deletar', post, method: :delete, data: { confirm: 'Você tem certeza?' } %>
            </td>
            <%break%>
          <%end%>
        <%end%>
      <%end%>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>